version: '3.8'

services:
  db:
    image: 'postgres:15.3'
    container_name: ff-db
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      - backend

  api:
    depends_on:
      - 'db'
    restart: always
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: ff-api
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=db
    volumes:
      - .:/app
    networks:
      - backend

networks:
  backend:
    name: food_facts_network

volumes:
  postgres:
