default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gluttony_control_development

test:
  <<: *default
  database: gluttony_control_test

production:
  <<: *default
  database: gluttony_control_production
  username: gluttony_control
  password: <%= ENV["GLUTTONY_CONTROL_DATABASE_PASSWORD"] %>
